#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="abc_car_traders")]
	public partial class DBDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertlogin(login instance);
    partial void Updatelogin(login instance);
    partial void Deletelogin(login instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    partial void Insertsparepart(sparepart instance);
    partial void Updatesparepart(sparepart instance);
    partial void Deletesparepart(sparepart instance);
    partial void InsertorderDetail(orderDetail instance);
    partial void UpdateorderDetail(orderDetail instance);
    partial void DeleteorderDetail(orderDetail instance);
    partial void Insertclient(client instance);
    partial void Updateclient(client instance);
    partial void Deleteclient(client instance);
    partial void Insertcar(car instance);
    partial void Updatecar(car instance);
    partial void Deletecar(car instance);
    #endregion
		
		public DBDataClassesDataContext() : 
				base(global::DAL.Properties.Settings.Default.abc_car_tradersConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<sparepart> spareparts
		{
			get
			{
				return this.GetTable<sparepart>();
			}
		}
		
		public System.Data.Linq.Table<orderDetail> orderDetails
		{
			get
			{
				return this.GetTable<orderDetail>();
			}
		}
		
		public System.Data.Linq.Table<client> clients
		{
			get
			{
				return this.GetTable<client>();
			}
		}
		
		public System.Data.Linq.Table<car> cars
		{
			get
			{
				return this.GetTable<car>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_id;
		
		private string _admin_name;
		
		private System.Nullable<int> _login_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void Onadmin_nameChanging(string value);
    partial void Onadmin_nameChanged();
    partial void Onlogin_idChanging(System.Nullable<int> value);
    partial void Onlogin_idChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string admin_name
		{
			get
			{
				return this._admin_name;
			}
			set
			{
				if ((this._admin_name != value))
				{
					this.Onadmin_nameChanging(value);
					this.SendPropertyChanging();
					this._admin_name = value;
					this.SendPropertyChanged("admin_name");
					this.Onadmin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_id", DbType="Int")]
		public System.Nullable<int> login_id
		{
			get
			{
				return this._login_id;
			}
			set
			{
				if ((this._login_id != value))
				{
					this.Onlogin_idChanging(value);
					this.SendPropertyChanging();
					this._login_id = value;
					this.SendPropertyChanged("login_id");
					this.Onlogin_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _login_id;
		
		private string _user_name;
		
		private string _password;
		
		private bool _isAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlogin_idChanging(int value);
    partial void Onlogin_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnisAdminChanging(bool value);
    partial void OnisAdminChanged();
    #endregion
		
		public login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int login_id
		{
			get
			{
				return this._login_id;
			}
			set
			{
				if ((this._login_id != value))
				{
					this.Onlogin_idChanging(value);
					this.SendPropertyChanging();
					this._login_id = value;
					this.SendPropertyChanged("login_id");
					this.Onlogin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit NOT NULL")]
		public bool isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private byte _status;
		
		private string _clt_name;
		
		private System.Nullable<int> _order_total_amount;
		
		private System.Nullable<int> _total_quantity;
		
		private string _payment_type;
		
		private System.Nullable<System.DateTime> _date_order_placed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    partial void Onclt_nameChanging(string value);
    partial void Onclt_nameChanged();
    partial void Onorder_total_amountChanging(System.Nullable<int> value);
    partial void Onorder_total_amountChanged();
    partial void Ontotal_quantityChanging(System.Nullable<int> value);
    partial void Ontotal_quantityChanged();
    partial void Onpayment_typeChanging(string value);
    partial void Onpayment_typeChanged();
    partial void Ondate_order_placedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_order_placedChanged();
    #endregion
		
		public order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_name", DbType="VarChar(50)")]
		public string clt_name
		{
			get
			{
				return this._clt_name;
			}
			set
			{
				if ((this._clt_name != value))
				{
					this.Onclt_nameChanging(value);
					this.SendPropertyChanging();
					this._clt_name = value;
					this.SendPropertyChanged("clt_name");
					this.Onclt_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_amount", DbType="Int")]
		public System.Nullable<int> order_total_amount
		{
			get
			{
				return this._order_total_amount;
			}
			set
			{
				if ((this._order_total_amount != value))
				{
					this.Onorder_total_amountChanging(value);
					this.SendPropertyChanging();
					this._order_total_amount = value;
					this.SendPropertyChanged("order_total_amount");
					this.Onorder_total_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_quantity", DbType="Int")]
		public System.Nullable<int> total_quantity
		{
			get
			{
				return this._total_quantity;
			}
			set
			{
				if ((this._total_quantity != value))
				{
					this.Ontotal_quantityChanging(value);
					this.SendPropertyChanging();
					this._total_quantity = value;
					this.SendPropertyChanged("total_quantity");
					this.Ontotal_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="VarChar(50)")]
		public string payment_type
		{
			get
			{
				return this._payment_type;
			}
			set
			{
				if ((this._payment_type != value))
				{
					this.Onpayment_typeChanging(value);
					this.SendPropertyChanging();
					this._payment_type = value;
					this.SendPropertyChanged("payment_type");
					this.Onpayment_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_order_placed", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_order_placed
		{
			get
			{
				return this._date_order_placed;
			}
			set
			{
				if ((this._date_order_placed != value))
				{
					this.Ondate_order_placedChanging(value);
					this.SendPropertyChanging();
					this._date_order_placed = value;
					this.SendPropertyChanged("date_order_placed");
					this.Ondate_order_placedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sparepart")]
	public partial class sparepart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _part_id;
		
		private string _part_name;
		
		private string _part_menufecturer;
		
		private string _part_warrenty;
		
		private System.Nullable<int> _part_price;
		
		private System.Nullable<int> _part_quentity;
		
		private string _image_path;
		
		private System.Nullable<System.DateTime> _date_added;
		
		private string _date_updated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpart_idChanging(int value);
    partial void Onpart_idChanged();
    partial void Onpart_nameChanging(string value);
    partial void Onpart_nameChanged();
    partial void Onpart_menufecturerChanging(string value);
    partial void Onpart_menufecturerChanged();
    partial void Onpart_warrentyChanging(string value);
    partial void Onpart_warrentyChanged();
    partial void Onpart_priceChanging(System.Nullable<int> value);
    partial void Onpart_priceChanged();
    partial void Onpart_quentityChanging(System.Nullable<int> value);
    partial void Onpart_quentityChanged();
    partial void Onimage_pathChanging(string value);
    partial void Onimage_pathChanged();
    partial void Ondate_addedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_addedChanged();
    partial void Ondate_updatedChanging(string value);
    partial void Ondate_updatedChanged();
    #endregion
		
		public sparepart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this.Onpart_idChanging(value);
					this.SendPropertyChanging();
					this._part_id = value;
					this.SendPropertyChanged("part_id");
					this.Onpart_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string part_name
		{
			get
			{
				return this._part_name;
			}
			set
			{
				if ((this._part_name != value))
				{
					this.Onpart_nameChanging(value);
					this.SendPropertyChanging();
					this._part_name = value;
					this.SendPropertyChanged("part_name");
					this.Onpart_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_menufecturer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string part_menufecturer
		{
			get
			{
				return this._part_menufecturer;
			}
			set
			{
				if ((this._part_menufecturer != value))
				{
					this.Onpart_menufecturerChanging(value);
					this.SendPropertyChanging();
					this._part_menufecturer = value;
					this.SendPropertyChanged("part_menufecturer");
					this.Onpart_menufecturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_warrenty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string part_warrenty
		{
			get
			{
				return this._part_warrenty;
			}
			set
			{
				if ((this._part_warrenty != value))
				{
					this.Onpart_warrentyChanging(value);
					this.SendPropertyChanging();
					this._part_warrenty = value;
					this.SendPropertyChanged("part_warrenty");
					this.Onpart_warrentyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_price", DbType="Int")]
		public System.Nullable<int> part_price
		{
			get
			{
				return this._part_price;
			}
			set
			{
				if ((this._part_price != value))
				{
					this.Onpart_priceChanging(value);
					this.SendPropertyChanging();
					this._part_price = value;
					this.SendPropertyChanged("part_price");
					this.Onpart_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_quentity", DbType="Int")]
		public System.Nullable<int> part_quentity
		{
			get
			{
				return this._part_quentity;
			}
			set
			{
				if ((this._part_quentity != value))
				{
					this.Onpart_quentityChanging(value);
					this.SendPropertyChanging();
					this._part_quentity = value;
					this.SendPropertyChanged("part_quentity");
					this.Onpart_quentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_path", DbType="NVarChar(MAX)")]
		public string image_path
		{
			get
			{
				return this._image_path;
			}
			set
			{
				if ((this._image_path != value))
				{
					this.Onimage_pathChanging(value);
					this.SendPropertyChanging();
					this._image_path = value;
					this.SendPropertyChanged("image_path");
					this.Onimage_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_added", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_added
		{
			get
			{
				return this._date_added;
			}
			set
			{
				if ((this._date_added != value))
				{
					this.Ondate_addedChanging(value);
					this.SendPropertyChanging();
					this._date_added = value;
					this.SendPropertyChanged("date_added");
					this.Ondate_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_updated", DbType="VarChar(50)")]
		public string date_updated
		{
			get
			{
				return this._date_updated;
			}
			set
			{
				if ((this._date_updated != value))
				{
					this.Ondate_updatedChanging(value);
					this.SendPropertyChanging();
					this._date_updated = value;
					this.SendPropertyChanged("date_updated");
					this.Ondate_updatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderDetails")]
	public partial class orderDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_Details_id;
		
		private System.Nullable<int> _Item_id;
		
		private string _Item_name;
		
		private string _Item_Type;
		
		private string _client_name;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<int> _pricePerItem;
		
		private System.Nullable<int> _total_qty_price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_Details_idChanging(int value);
    partial void Onorder_Details_idChanged();
    partial void OnItem_idChanging(System.Nullable<int> value);
    partial void OnItem_idChanged();
    partial void OnItem_nameChanging(string value);
    partial void OnItem_nameChanged();
    partial void OnItem_TypeChanging(string value);
    partial void OnItem_TypeChanged();
    partial void Onclient_nameChanging(string value);
    partial void Onclient_nameChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnpricePerItemChanging(System.Nullable<int> value);
    partial void OnpricePerItemChanged();
    partial void Ontotal_qty_priceChanging(System.Nullable<int> value);
    partial void Ontotal_qty_priceChanged();
    #endregion
		
		public orderDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_Details_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int order_Details_id
		{
			get
			{
				return this._order_Details_id;
			}
			set
			{
				if ((this._order_Details_id != value))
				{
					this.Onorder_Details_idChanging(value);
					this.SendPropertyChanging();
					this._order_Details_id = value;
					this.SendPropertyChanged("order_Details_id");
					this.Onorder_Details_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_id", DbType="Int")]
		public System.Nullable<int> Item_id
		{
			get
			{
				return this._Item_id;
			}
			set
			{
				if ((this._Item_id != value))
				{
					this.OnItem_idChanging(value);
					this.SendPropertyChanging();
					this._Item_id = value;
					this.SendPropertyChanged("Item_id");
					this.OnItem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_name", DbType="VarChar(50)")]
		public string Item_name
		{
			get
			{
				return this._Item_name;
			}
			set
			{
				if ((this._Item_name != value))
				{
					this.OnItem_nameChanging(value);
					this.SendPropertyChanging();
					this._Item_name = value;
					this.SendPropertyChanged("Item_name");
					this.OnItem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type", DbType="VarChar(50)")]
		public string Item_Type
		{
			get
			{
				return this._Item_Type;
			}
			set
			{
				if ((this._Item_Type != value))
				{
					this.OnItem_TypeChanging(value);
					this.SendPropertyChanging();
					this._Item_Type = value;
					this.SendPropertyChanged("Item_Type");
					this.OnItem_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_name", DbType="VarChar(50)")]
		public string client_name
		{
			get
			{
				return this._client_name;
			}
			set
			{
				if ((this._client_name != value))
				{
					this.Onclient_nameChanging(value);
					this.SendPropertyChanging();
					this._client_name = value;
					this.SendPropertyChanged("client_name");
					this.Onclient_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pricePerItem", DbType="Int")]
		public System.Nullable<int> pricePerItem
		{
			get
			{
				return this._pricePerItem;
			}
			set
			{
				if ((this._pricePerItem != value))
				{
					this.OnpricePerItemChanging(value);
					this.SendPropertyChanging();
					this._pricePerItem = value;
					this.SendPropertyChanged("pricePerItem");
					this.OnpricePerItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_qty_price", DbType="Int")]
		public System.Nullable<int> total_qty_price
		{
			get
			{
				return this._total_qty_price;
			}
			set
			{
				if ((this._total_qty_price != value))
				{
					this.Ontotal_qty_priceChanging(value);
					this.SendPropertyChanging();
					this._total_qty_price = value;
					this.SendPropertyChanged("total_qty_price");
					this.Ontotal_qty_priceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.client")]
	public partial class client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _clt_id;
		
		private string _clt_email;
		
		private string _clt_address;
		
		private string _clt_mobileNumber;
		
		private System.Nullable<System.DateTime> _clt_registered_date;
		
		private string _clt_updated_date;
		
		private System.Nullable<int> _login_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onclt_idChanging(int value);
    partial void Onclt_idChanged();
    partial void Onclt_emailChanging(string value);
    partial void Onclt_emailChanged();
    partial void Onclt_addressChanging(string value);
    partial void Onclt_addressChanged();
    partial void Onclt_mobileNumberChanging(string value);
    partial void Onclt_mobileNumberChanged();
    partial void Onclt_registered_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onclt_registered_dateChanged();
    partial void Onclt_updated_dateChanging(string value);
    partial void Onclt_updated_dateChanged();
    partial void Onlogin_idChanging(System.Nullable<int> value);
    partial void Onlogin_idChanged();
    #endregion
		
		public client()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int clt_id
		{
			get
			{
				return this._clt_id;
			}
			set
			{
				if ((this._clt_id != value))
				{
					this.Onclt_idChanging(value);
					this.SendPropertyChanging();
					this._clt_id = value;
					this.SendPropertyChanged("clt_id");
					this.Onclt_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_email", DbType="VarChar(MAX)")]
		public string clt_email
		{
			get
			{
				return this._clt_email;
			}
			set
			{
				if ((this._clt_email != value))
				{
					this.Onclt_emailChanging(value);
					this.SendPropertyChanging();
					this._clt_email = value;
					this.SendPropertyChanged("clt_email");
					this.Onclt_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_address", DbType="VarChar(MAX)")]
		public string clt_address
		{
			get
			{
				return this._clt_address;
			}
			set
			{
				if ((this._clt_address != value))
				{
					this.Onclt_addressChanging(value);
					this.SendPropertyChanging();
					this._clt_address = value;
					this.SendPropertyChanged("clt_address");
					this.Onclt_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_mobileNumber", DbType="VarChar(MAX)")]
		public string clt_mobileNumber
		{
			get
			{
				return this._clt_mobileNumber;
			}
			set
			{
				if ((this._clt_mobileNumber != value))
				{
					this.Onclt_mobileNumberChanging(value);
					this.SendPropertyChanging();
					this._clt_mobileNumber = value;
					this.SendPropertyChanged("clt_mobileNumber");
					this.Onclt_mobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_registered_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> clt_registered_date
		{
			get
			{
				return this._clt_registered_date;
			}
			set
			{
				if ((this._clt_registered_date != value))
				{
					this.Onclt_registered_dateChanging(value);
					this.SendPropertyChanging();
					this._clt_registered_date = value;
					this.SendPropertyChanged("clt_registered_date");
					this.Onclt_registered_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clt_updated_date", DbType="VarChar(50)")]
		public string clt_updated_date
		{
			get
			{
				return this._clt_updated_date;
			}
			set
			{
				if ((this._clt_updated_date != value))
				{
					this.Onclt_updated_dateChanging(value);
					this.SendPropertyChanging();
					this._clt_updated_date = value;
					this.SendPropertyChanged("clt_updated_date");
					this.Onclt_updated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_id", DbType="Int")]
		public System.Nullable<int> login_id
		{
			get
			{
				return this._login_id;
			}
			set
			{
				if ((this._login_id != value))
				{
					this.Onlogin_idChanging(value);
					this.SendPropertyChanging();
					this._login_id = value;
					this.SendPropertyChanged("login_id");
					this.Onlogin_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.car")]
	public partial class car : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _car_id;
		
		private string _modelname;
		
		private string _brand;
		
		private string _color;
		
		private string _fueltype;
		
		private string _availability;
		
		private string _type;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<System.DateTime> _added_date;
		
		private string _image_path;
		
		private string _updated_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncar_idChanging(int value);
    partial void Oncar_idChanged();
    partial void OnmodelnameChanging(string value);
    partial void OnmodelnameChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OnfueltypeChanging(string value);
    partial void OnfueltypeChanged();
    partial void OnavailabilityChanging(string value);
    partial void OnavailabilityChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void Onadded_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onadded_dateChanged();
    partial void Onimage_pathChanging(string value);
    partial void Onimage_pathChanged();
    partial void Onupdated_dateChanging(string value);
    partial void Onupdated_dateChanged();
    #endregion
		
		public car()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelname", DbType="VarChar(50)")]
		public string modelname
		{
			get
			{
				return this._modelname;
			}
			set
			{
				if ((this._modelname != value))
				{
					this.OnmodelnameChanging(value);
					this.SendPropertyChanging();
					this._modelname = value;
					this.SendPropertyChanged("modelname");
					this.OnmodelnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(50)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fueltype", DbType="VarChar(50)")]
		public string fueltype
		{
			get
			{
				return this._fueltype;
			}
			set
			{
				if ((this._fueltype != value))
				{
					this.OnfueltypeChanging(value);
					this.SendPropertyChanging();
					this._fueltype = value;
					this.SendPropertyChanged("fueltype");
					this.OnfueltypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_availability", DbType="VarChar(50)")]
		public string availability
		{
			get
			{
				return this._availability;
			}
			set
			{
				if ((this._availability != value))
				{
					this.OnavailabilityChanging(value);
					this.SendPropertyChanging();
					this._availability = value;
					this.SendPropertyChanged("availability");
					this.OnavailabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_added_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> added_date
		{
			get
			{
				return this._added_date;
			}
			set
			{
				if ((this._added_date != value))
				{
					this.Onadded_dateChanging(value);
					this.SendPropertyChanging();
					this._added_date = value;
					this.SendPropertyChanged("added_date");
					this.Onadded_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_path", DbType="NVarChar(MAX)")]
		public string image_path
		{
			get
			{
				return this._image_path;
			}
			set
			{
				if ((this._image_path != value))
				{
					this.Onimage_pathChanging(value);
					this.SendPropertyChanging();
					this._image_path = value;
					this.SendPropertyChanged("image_path");
					this.Onimage_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_date", DbType="VarChar(50)")]
		public string updated_date
		{
			get
			{
				return this._updated_date;
			}
			set
			{
				if ((this._updated_date != value))
				{
					this.Onupdated_dateChanging(value);
					this.SendPropertyChanging();
					this._updated_date = value;
					this.SendPropertyChanged("updated_date");
					this.Onupdated_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
